name: CI

on: [push, pull_request]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-ubuntu-latest-cmake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: cmake and make
        run: |
          sudo apt-get install -y cmake libssl-dev
          mkdir -p build-release
          cd build-release
          cmake -DCMAKE_BUILD_TYPE=Release .. -DBUILD_TLS=yes -DBUILD_UNIT_TESTS=yes
          make -j$(nproc)
      - name: test
        run: |
          sudo apt-get install -y tcl8.6 tclx
          ln -sf $(pwd)/build-release/bin/valkey-server $(pwd)/src/valkey-server
          ln -sf $(pwd)/build-release/bin/valkey-cli $(pwd)/src/valkey-cli
          ln -sf $(pwd)/build-release/bin/valkey-benchmark $(pwd)/src/valkey-benchmark
          ln -sf $(pwd)/build-release/bin/valkey-server $(pwd)/src/valkey-check-aof
          ln -sf $(pwd)/build-release/bin/valkey-server $(pwd)/src/valkey-check-rdb
          ln -sf $(pwd)/build-release/bin/valkey-server $(pwd)/src/valkey-sentinel
          ./runtest --verbose --tags -slow --dump-logs
      - name: unit tests
        run: |
          ./build-release/bin/valkey-unit-tests --seed D7E26CF9E0E78062C09629FF4791658E97C9A00E5C752F0CE933655887184709AD7A57A0E9F84C090C365A51EED2B6855075C7436F708B9C47BA13684ECCFDF0
